spring:
  profiles:
    active: mysql

  batch:
    job:
      # Program arguments 로 job.name 값이 넘어오면 해당 값과 일치하는 Job 만 실행
      # job.name 이 있으면 job.name 할당 없으면 NONE 할당
      # NONE 이 할당되면 모든 배치 실행 X
      names: ${job.name:NONE}
#  jpa:
#    hibernate:
#      ddl-auto: update


logging:
  level:
    org.springframework.batch: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/springbatch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver