spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study
    password: study
    username: study

  jpa:
    hibernate:
      ddl-auto: update
