spring:
  profiles:
    active: chaos-monkey
  datasource:
    url: jdbc:h2:tcp://localhost/~/appcenterstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, chaosmonkey
chaos:
  monkey:
    enabled: true
    watcher:
      repository: true
      service: true
    assaults:
      exception:
        type: java.lang.RuntimeException
      exceptions-active: true
      level: 3
      latency-active: false


