version: '3.7'
services:
  license-service:
    image: license-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "license-service"

networks:
  backend:
    driver: bridge
