spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: /Users/juhwan/temp/
      max-request-size: 30MB
      max-file-size: 10MB

upload:
  path: /Users/juhwan/temp/
