spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

# JdbcTemplate SQL log
logging:
  level:
    org.springframework.jdbc: debug
