spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
    # JdbcTemplate SQL log
    org.springframework.jdbc: debug
    # MyBatis
    hello.itemservice.repository.mybatis: trace

# MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true

