spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

#jdbcTemplate log
logging:
  level:
    org.springframework.jdbc: debug
    hello.itemservice.repository.mybatis: trace

#MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true


